### ISSUE TITLE
我尝试使用着自己把这个theme fork到我自己的仓库并且作出修改，但是并不能生效

### ISSUE THREAD

**Issue by Yecgaa1** [wu-kan/jekyll-theme-WuK#3]
```
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源
  - jekyll-remote-theme # 使用remote_theme插件实现主题的前后分离，详见<https://github.com/benbalter/jekyll-remote-theme/>

remote_theme: https://github.com/xutongxin1/jekyll-theme-WuK@4.0.1 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README
```
然后由于我博客也是fork你的项目，我尝试着照葫芦画瓢
但是Github告诉我
`remote_theme: https://github.com/xutongxin1/jekyll-theme-WuK@4.0.1`
是错误的
希望你可以告诉我我该怎么改
最后再次感谢你提供了一个这么好的blog模板

**Comment by hc495** [comment]
您好。
我在本地尝试用上述配置构建了页面，没有发现异常。
而且我修改了我页面的YAML的`remote_theme`项为`https://github.com/xutongxin1/jekyll-theme-WuK@4.0.1`，GitHub Pages也生成成功了。
您也请测试一下这个错误是否可以复现？

**Comment by Yecgaa1** [comment]
> 您好。
> 我在本地尝试用上述配置构建了页面，没有发现异常。
> 而且我修改了我页面的YAML的`remote_theme`项为`https://github.com/xutongxin1/jekyll-theme-WuK@4.0.1`，GitHub Pages也生成成功了。
> 您也请测试一下这个错误是否可以复现？
好的，这是我在使用之前的渲染模板时
![image](https://user-images.githubusercontent.com/38446391/100497343-d9dd9e00-3195-11eb-8fcc-48ce61f00a1f.png)
这是我在修改为自己fork的主题时
![image](https://user-images.githubusercontent.com/38446391/100497396-4e184180-3196-11eb-969c-33138fe9cb01.png)

贴上我的改动：
![image](https://user-images.githubusercontent.com/38446391/100497448-a8b19d80-3196-11eb-9773-551915635739.png)

**Comment by hc495** [comment]
谢谢。
因为手头没有调试环境，我不知道以下判断是否正确：
您的YAML配置文件中似乎把`jekyll-theme-WuK`数组提到了过高的位置，而在4.0.1版本下的渲染是基于`page`标签而不是`site`标签的。您可以使用如下的层级结构来测试问题是否继续存在：
```yaml
defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      categories: "_posts"
      jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
        default:
....
```
今天的晚些时候回到家里我可以测试一下上述想法是否正确。
